# Generated by Django 3.2.8 on 2021-10-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pic',
        ),
    ]
