# Generated by Django 3.2.9 on 2021-11-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_artlinkmodel_artphotosmodel_navbarmodel_progskillsmodel_sociallinkmodel_softskillsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='IDname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
